# .github/workflows/lint.yml
name: Ruff Linter

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install ruff
      - name: Run ruff
        uses: astral-sh/ruff-action@v1
        with:
          # 可选: 指定 ruff 的版本
          version: "latest" 